SELECT DISTINCT PLAYLIST.Name
FROM PLAYLIST
JOIN SONG
  ON PLAYLIST.Song = SONG.ID
JOIN ALBUM
  ON SONG.Album = ALBUM.ID
JOIN ARTIST
  ON ALBUM.Artist = ARTIST.ID
WHERE ALBUM.Year < 2001 AND ARTIST.Label "UMG"
